import { QuestionPool, AnswerChecker, ScoreManager } from 'https://tt-sensei.github.io/edu-components/index.js';
import { renderCard, cardImage } from './card-render.js';

let active=null;
const pick=(list)=>list[Math.floor(Math.random()*list.length)];
function cardFromId(id){const card=(window.BATTLE_CARDS||[]).find((item)=>item.id===id||item.monsterId===id);const monsterId=card?.monsterId||id;const monster=(window.BATTLE_MONSTERS||[]).find((item)=>item.id===monsterId);if(!monster)return null;return {...monster,...(card||{}),id:card?.id||monster.id,monsterId:monster.id,name:card?.name||monster.name,src:cardImage({...monster,...(card||{})})||monster.src}}
function normalizeTeam(team){const ids=Array.isArray(team)?team:[];const normalized=ids.map((item)=>typeof item==='string'?cardFromId(item):cardFromId(item?.id||item?.monsterId)).filter(Boolean);return normalized.length?normalized.slice(0,3):['purun-slime','komorin-bat','kinoko'].map(cardFromId).filter(Boolean)}
function enemyRankForGrade(grade){const g=Number(grade)||1;return g<=2?'zako':g<=4?'evolved':'boss'}
function subjectMonster(subject,grade){const all=window.BATTLE_MONSTERS||[];const rank=enemyRankForGrade(grade);const rankOnly=all.filter((m)=>m.rank===rank);const pool=rankOnly.length?rankOnly:all;const same=pool.filter((m)=>m.subject===subject);const preferred=same.length?same:pool;const unused=preferred.filter((m)=>!active?.usedMonsterIds?.includes(m.id));return pick(unused.length?unused:preferred)}
function bestCardIndex(){const i=active.team.findIndex(c=>c.subject===active.monster.subject);return i>=0?i:0}
function render(){document.getElementById('battleScreen').innerHTML=`<div class="battle-shell"><aside class="battle-side"><div class="panel"><div class="battle-side-title">🃏 じぶんのチーム</div><div id="battleTeam" class="battle-team"></div><p class="battle-team-help">カードをえらんで出撃！<br>モンスターの弱点と同じ教科なら、2ダメージ！</p></div><button id="battleQuit" class="btn small battle-quit">← やめる</button></aside><section class="battle-arena"><div class="battle-top"><span id="battleProgress">1 / 3</span><span id="battleSubject"></span></div><div class="battle-fighters"><div class="fighter player-fighter"><div class="fighter-label">じぶんのカード</div><div id="playerCard" class="fighter-card"></div></div><div class="vs">VS</div><div class="fighter"><div class="fighter-label enemy-label">モンスター</div><img id="enemyImg" class="enemy-img" alt=""><b id="enemyName" class="enemy-name"></b><div id="enemyWeakness" class="enemy-weakness"></div></div></div><div class="enemy-hp"><div><b id="enemyHpName">モンスター</b><span><b id="enemyHp">1</b> / <b id="enemyMax">1</b></span></div><div class="hp-track"><i id="enemyBar"></i></div></div><div id="battleFeedback" class="battle-feedback" aria-live="polite"></div></section><section class="panel battle-question"><span id="questionBadge" class="battle-badge"></span><div id="questionText" class="battle-qtext"></div><div id="questionHint" class="battle-hint"></div><div id="questionChoices" class="battle-choices"></div><p class="battle-help">正解するとカードが攻撃！ 得意な教科のカードなら選択肢が3つに。</p></section><div id="battleResult" class="battle-result" hidden><div class="battle-result-box"><div id="resultEmoji" class="result-emoji"></div><h2 id="resultTitle"></h2><p id="resultText"></p><button id="resultHome" class="btn primary">ホームへ</button></div></div></div>`}
function drawTeam(){const el=document.getElementById('battleTeam');el.innerHTML=active.team.map((c,i)=>`<button type="button" class="battle-mini ${i===active.cardIndex?'active':''}" data-team-index="${i}" aria-pressed="${i===active.cardIndex}">${renderCard(c,{showInfo:false,mini:true})}<span><b>${c.name}</b><small>${c.subject}・${i===active.cardIndex?'出撃中':'待機'}</small></span></button>`).join('');const c=active.team[active.cardIndex];document.getElementById('playerCard').innerHTML=renderCard(c,{showInfo:true,className:'battle-card-large'})}
function drawMonster(){const m=active.monster;document.getElementById('battleProgress').textContent=`${active.monsterIndex+1} / 3`;document.getElementById('battleSubject').textContent=active.subject;document.getElementById('enemyImg').src=cardImage(m)||m.src;document.getElementById('enemyImg').alt=m.name;document.getElementById('enemyName').textContent=m.name;document.getElementById('enemyWeakness').textContent=`弱点：${m.subject}`;document.getElementById('enemyHpName').textContent=m.name;document.getElementById('enemyHp').textContent=m.hp;document.getElementById('enemyMax').textContent=m.hp;document.getElementById('enemyBar').style.width='100%'}
function feedback(text,type){const el=document.getElementById('battleFeedback');el.className=`battle-feedback ${type} show`;el.textContent=text;setTimeout(()=>el.classList.remove('show'),650)}
function updateQuestionChoices(){if(!active?.question)return;const q=active.question;const choices=Array.isArray(q.choices)?q.choices:[];const reduced=active.team[active.cardIndex]?.subject===active.subject&&choices.length>3;const visible=reduced?[...choices].filter((c)=>c!==q.answer).sort(()=>Math.random()-0.5).slice(0,2).concat(q.answer):choices;document.getElementById('questionChoices').innerHTML=visible.map((c,i)=>`<button class="battle-choice" data-index="${i}" data-answer="${String(c).replace(/"/g,'&quot;')}">${c}</button>`).join('');document.getElementById('questionHint').dataset.reduced=reduced?'1':'0'}
function nextQuestion(){if(!active?.running)return;let q=active.pool.next();if(!q){active.pool.reset();q=active.pool.next()}if(!q)return finish(false);active.question=q;document.getElementById('questionBadge').textContent=`${active.grade}年・${active.subject}`;document.getElementById('questionText').textContent=q.question||'';document.getElementById('questionHint').textContent=q.hint||'ヒント：問題をもう一度ゆっくり読もう。';document.getElementById('questionHint').classList.remove('show');updateQuestionChoices();active.locked=false}
function animate(cls,target){if(!target)return;target.classList.remove(cls);void target.offsetWidth;target.classList.add(cls)}
function selectCard(index){if(!active?.running||active.locked||index<0||index>=active.team.length)return;active.cardIndex=index;drawTeam();updateQuestionChoices();feedback(active.team[index].subject===active.monster.subject?'弱点カード！':'このカードで攻撃','card')}
function answer(index){if(!active||active.locked||!active.running)return;const q=active.question;const button=document.querySelector(`.battle-choice[data-index="${index}"]`);const selected=button?.dataset.answer;if(selected===undefined)return;active.locked=true;document.querySelectorAll('.battle-choice').forEach((b)=>{b.disabled=true});const correct=active.checker.check(selected,q.answer,{detail:{questionId:q.id,grade:active.grade,subject:active.subject}});if(correct){active.score.correct(10);active.onPoints(10);feedback('せいかい！','good');animate('attack',document.getElementById('playerCard'));setTimeout(()=>animate('hit',document.getElementById('enemyImg')),170);const superEffective=active.team[active.cardIndex].subject===active.monster.subject;const damage=superEffective?2:1;if(superEffective)active.onPoints(5);active.hp=Math.max(0,active.hp-damage);document.getElementById('enemyHp').textContent=active.hp;document.getElementById('enemyBar').style.width=`${active.hp/active.monster.hp*100}%`;if(damage===2)feedback('こうかばつぐん！ 2ダメージ！','great');if(active.hp<=0){document.getElementById('enemyImg').classList.add('defeat');setTimeout(()=>{if(!active?.running)return;active.monsterIndex+=1;if(active.monsterIndex>=3)finish(true);else{active.usedMonsterIds.push(active.monster.id);active.monster=subjectMonster(active.subject,active.grade);if(!active.monster)return finish(false);active.hp=active.monster.hp;active.cardIndex=bestCardIndex();drawTeam();drawMonster();nextQuestion()}},650)}else setTimeout(nextQuestion,520)}else{active.score.wrong(0);active.onWrong(q);feedback('もう一度！','bad');animate('hurt',document.getElementById('playerCard'));document.getElementById('questionHint').classList.add('show');setTimeout(()=>{if(!active?.running)return;active.locked=false;document.querySelectorAll('.battle-choice').forEach((b)=>{b.disabled=false})},550)}}
function finish(win){if(!active)return;active.running=false;active.locked=true;if(win)active.onPoints(20);const r=document.getElementById('battleResult');r.hidden=false;document.getElementById('resultEmoji').textContent=win?'🏆':'📖';document.getElementById('resultTitle').textContent=win?'バトルクリア！':'バトル終了';document.getElementById('resultText').textContent=win?`3体撃破！ 正解 ${active.score.correctCount}問　+20P`:'問題データを確認して、もう一度挑戦しよう。';document.getElementById('resultHome').onclick=()=>active?.onHome()}
export function startBattle({grade,subject,questions,team,onPoints,onWrong,onHome}){stopBattle();const normalizedTeam=normalizeTeam(team);const usableQuestions=Array.isArray(questions)?questions.filter((q)=>Array.isArray(q.choices)&&q.choices.length>0):[];if(!usableQuestions.length){onHome?.();return}render();active={grade,subject,team:normalizedTeam,onPoints,onWrong,onHome,monsterIndex:0,usedMonsterIds:[],monster:subjectMonster(subject,grade),hp:0,question:null,locked:false,running:true,cardIndex:0,pool:new QuestionPool(usableQuestions,{mode:'random'}),checker:new AnswerChecker({eventTarget:window}),score:new ScoreManager({eventTarget:window})};if(!active.monster)return finish(false);active.usedMonsterIds.push(active.monster.id);active.cardIndex=bestCardIndex();active.hp=active.monster.hp;drawTeam();drawMonster();nextQuestion();document.getElementById('battleQuit').onclick=onHome;document.getElementById('battleTeam').addEventListener('click',(e)=>{const button=e.target.closest('[data-team-index]');if(button)selectCard(Number(button.dataset.teamIndex))});document.getElementById('questionChoices').addEventListener('click',(e)=>{const button=e.target.closest('.battle-choice');if(button)answer(Number(button.dataset.index))})}
export function stopBattle(){active=null}
export function getBattleState(){return active}
